pipeline {
    agent none
    stages {
        stage('checkserver') {
            agent { label 'ubuntu' }
            steps {
                script {
                    sh 'pwd'
                    sh 'whoami'
                    sh 'cat /etc/os-release'
                }
            }
        }
        stage('maven') {
            agent {label 'ubuntu'}
                {docker { image 'maven:3.9.9-amazoncorretto-8-debian' }
            }
            steps {
                sh "touch \$BUILD_ID-\$(date)"
                sh 'mvn --version'
            }
        }
    }
}