pipeline {
    agent any  // Define pipeline agent at the top level
    
    stages {
        stage('checkserver') {
            steps {
                sh 'echo "Checking server status"'
                sh 'whoami'
                sh 'cat /etc/*release'
            }
        }

        stage('mvn') {
            steps {
                script {
                    docker.image('maven:3.9.9-amazoncorretto-8-debian').inside {
                        sh 'mvn --version'
                    }
                }
            }
        }
    }
}
