pipeline {
    agent any
    tools {
        maven 'M2_HOME' //opt/maven
        jdk 'JAVA_HOME'      
    }

    environment {

        AWS_REGION = 'us-east-1'
        AWS_REPO = '180294207776.dkr.ecr.us-east-1.amazonaws.com/jenkins-ci'
        AWS_URL = '180294207776.dkr.ecr.us-east-1.amazonaws.com'
        BRANCH_NAME= 'main'
        GIT_PROJECT_URL = 'https://github.com/henrykrop2022/pet-clinic-java.git'
        GIT_CRED = 'github-accessID'
        SONAQUBE_CRED = 'sonarqube-credentials'
        SCANNER_HOME= tool 'sonar'
        SONAR_URL = 'http://98.80.8.63:9000/'
        SONAQUBE_INSTALLATION = 'sonar'
        APP_NAME = 'pet-clinic-java'
        JFROG_CRED = 'jfrog-cred'
        ARTIFACTPATH = 'target/*.jar'
        ARTIFACTORY_URL = 'http://98.80.8.63:8082/artifactory'
        REPO = 'devops'
        ARTIFACTTARGETPATH = "release_${BUILD_ID}.jar"
        DOCKER_REPO = "${REPO_URL}/${DOCKER_REPO_NAME}"
        DOCKER_REPO_NAME = "${APP_NAME}"
        HELMARTIFACTPATH = "petclinic-${BUILD_ID}.tgz"
        HELMARTIFACTTARGET = "heml/petclinic-${BUILD_ID}.tgz"
        KUBERNETES_CRED = 'KUBERNETES_CRED'
        KUBERNETES_URL = 'https://104.237.133.213:6443'
    }
    stages {
        // stage('Cleanup Workspace') {
        //     steps {
        //         deleteDir() // Clears old workspace files
        //     }
        // }
        stage('Git Checkout'){ // Cloning the code from the repository
            steps{
                git branch: "${BRANCH_NAME}", credentialsId: "${GIT_CRED}", \
                url: "${GIT_PROJECT_URL}"
            }
        }
        /*
        stage('CodeScan') {
            steps {
                sh "trivy fs --format table -o maven_dependency.html ."       
            }
        }
        stage('Unit Test'){
            steps{
                sh 'mvn clean package -DskipTests=true'
                sh 'mvn compile -DskipTests=true'
            }
        }
        stage('SonarQube Scan') {    
                steps {
                  withSonarQubeEnv(credentialsId: "${SONAQUBE_CRED}", \
                installationName: "${SONAQUBE_INSTALLATION}" ) {
              sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=${APP_NAME} -Dsonar.projectKey=${APP_NAME} \
                   -Dsonar.java.binaries=. '''
                }
            }
        }
        stage('Quality Gate Check'){
            steps{
              script{
                 waitForQualityGate abortPipeline: false, credentialsId: "${SONAQUBE_CRED}" 
              }
            }
        }
        //  stage('Code Package'){
        //     steps{
        //         sh 'mvn package -Dcheckstyle.skip=true'
        //     }
        // }
        stage('Upload Jar to Jfrog'){
            steps{
                withCredentials([usernamePassword(credentialsId: "${JFROG_CRED}", \
                 usernameVariable: 'ARTIFACTORY_USER', passwordVariable: 'ARTIFACTORY_PASSWORD')]) {
                    script {
                        // Define the artifact path and target location
                        //def artifactPath = 'target/*.jar'
                        //def targetPath = "release_${BUILD_ID}.jar"

                        // Upload the artifact using curl
                        sh """ curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} \
                                  -T ${ARTIFACTPATH} \
                                 ${ARTIFACTORY_URL}/${REPO}/${ARTIFACTTARGETPATH} """
                        // sh ''' curl -u $ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD -T target/*.jar http://54.198.102.162:8082/artifactory/devops/release_38.jar
// ''' 
                   }  
                }
            }
        }
        stage('CodeLogin') {
            steps {
                sh " aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_URL"
            }
        }
        stage('DockerImageBuild') {
            steps {
                sh ' docker build -t jenkins-ci .'
                sh ' docker build -t imageversion .'
            }
        }
        stage('DockerImageTag') {
            steps {
                sh "docker tag jenkins-ci:latest $AWS_REPO:latest"
                sh "docker tag imageversion $AWS_REPO:v1.$BUILD_NUMBER"
            }
        }
        stage('Docker PushImage to ECR') {
            steps {
               sh "docker push $AWS_REPO:latest"
                sh "docker push $AWS_REPO:v1.$BUILD_NUMBER" 
            }
        */
        stage('Chart Version Update'){
            steps{
                sh "python3 setup_scripts/chartUpdate.py ${BUILD_ID}" 
           
           }
        } 
        stage('Package Helm'){
            steps{
                sh 'helm package petclinic'
         }
      }
       stage('Upload helm package to Jfrog'){
            steps{
                 withCredentials([usernamePassword(credentialsId: "${JFROG_CRED}", \
                 usernameVariable: 'ARTIFACTORY_USER', passwordVariable: 'ARTIFACTORY_PASSWORD')]) {
                    script {
                        // Define the artifact path and target location
                        //def artifactPath = 'geo-app-${BUILD_ID}.tgz'
                        //def targetPath = "heml/geo-app-${BUILD_ID}.tgz"

                        // Upload the artifact using curl
                        sh """
                            curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} \
                                 -T ${HELMARTIFACTPATH} \
                                 ${ARTIFACTORY_URL}/${REPO}/${HELMARTIFACTTARGET}
                        """
               }
             }
          } 
       }
    }
}